export const ANALYTICS_SPORTS = [
  'padel',
  'futsal',
  'gaming',
  'snooker',
  'cricket',
  'table_tennis',
] as const;

export const ANALYTICS_SOURCES = [
  'map',
  'venue_list',
  'search_results',
  'venue_details',
  'drawer',
  'checkout',
] as const;

export const CLIENT_EVENT_NAMES = [
  'app_session_ready',
  'screen_view',
  'login',
  'login_failed',
  'sign_up',
  'sign_up_failed',
  'venue_search',
  'venue_search_results',
  'venue_selected',
  'venue_details_viewed',
  'booking_started',
  'availability_checked',
  'begin_checkout',
  'add_payment_info',
  'purchase',
  'booking_failed',
  'category_selected',
  'city_selected',
  'venue_list_opened',
  'booking_option_selected',
  'login_required_shown',
  'login_required_selected',
  'tournament_selected',
  'tournament_register_success',
  'tournament_register_failed',
  'tournament_payment_success',
  'tournament_payment_failed',
  'profile_action_selected',
  'order_selected',
  'faq_item_opened',
  'language_changed',
  'support_link_opened',
] as const;

export const SERVER_EVENT_NAMES = [
  'booking_created_server',
  'booking_cancelled_server',
  'booking_refunded_server',
  'payment_status_changed_server',
  'tournament_registration_created_server',
  'canteen_order_created_server',
  'canteen_order_status_changed_server',
] as const;

export const VENDOR_CLIENT_EVENT_NAMES = [
  'navigation_tab_selected',
  'analytics_period_changed',
  'analytics_refreshed',
  'business_link_copied',
  'business_link_shared',
  'analytics_detail_opened',
  'booking_create_started',
  'booking_create_completed',
  'booking_create_failed',
  'booking_opened',
  'booking_payment_updated',
  'booking_checked_out',
  'search_used',
  'filter_applied',
  'retry_selected',
  'location_opened',
  'location_create_completed',
  'location_update_completed',
  'facility_create_completed',
  'facility_update_completed',
  'user_create_completed',
  'user_update_completed',
  'user_status_changed',
  'customer_opened',
  'asset_create_completed',
  'asset_update_completed',
  'asset_delete_completed',
  'low_stock_viewed',
  'expense_create_completed',
  'expense_update_completed',
  'canteen_item_create_completed',
  'canteen_item_update_completed',
  'tournament_create_started',
  'tournament_create_completed',
  'tournament_registration_updated',
  'tournament_stage_generated',
  'match_score_saved',
  'theme_changed',
  'profile_photo_changed',
  'team_access_opened',
  'booking_slots_opened',
] as const;

export const ALLOWED_EVENT_NAMES = new Set<string>([
  ...CLIENT_EVENT_NAMES,
  ...SERVER_EVENT_NAMES,
  ...VENDOR_CLIENT_EVENT_NAMES,
]);

const VENDOR_EVENT_NAME_SET = new Set<string>(VENDOR_CLIENT_EVENT_NAMES);

const EVENT_PROPERTY_KEYS: Record<string, readonly string[]> = {
  app_session_ready: ['account_type'],
  screen_view: ['route', 'sport', 'flow_stage'],
  login: ['method'],
  login_failed: ['method', 'error_code', 'error_name', 'status_code'],
  sign_up: ['method'],
  sign_up_failed: ['method', 'error_code', 'error_name', 'status_code'],
  venue_search: ['search_type', 'city', 'sport'],
  venue_search_results: ['search_type', 'sport', 'result_count'],
  venue_selected: ['venue_id', 'sport', 'source'],
  venue_details_viewed: ['venue_id', 'sport'],
  booking_started: ['venue_id', 'sport', 'source'],
  availability_checked: ['venue_id', 'facility_type', 'result_count'],
  begin_checkout: ['venue_id', 'sport', 'value', 'currency'],
  add_payment_info: ['sport', 'payment_type', 'value', 'currency'],
  purchase: ['transaction_id', 'venue_id', 'sport', 'value', 'currency'],
  booking_failed: ['venue_id', 'sport', 'error_code', 'error_name', 'status_code'],
  category_selected: ['sport'],
  city_selected: ['city_id', 'city'],
  venue_list_opened: ['sport', 'result_count'],
  booking_option_selected: ['option_type', 'option_id', 'date', 'time'],
  login_required_shown: ['source'],
  login_required_selected: ['source'],
  tournament_selected: ['tournament_id', 'sport'],
  tournament_register_success: ['tournament_id', 'registration_id'],
  tournament_register_failed: [
    'tournament_id',
    'error_code',
    'error_name',
    'status_code',
  ],
  tournament_payment_success: ['registration_id', 'payment_method'],
  tournament_payment_failed: [
    'registration_id',
    'payment_method',
    'error_code',
    'error_name',
    'status_code',
  ],
  profile_action_selected: ['action'],
  order_selected: ['booking_id', 'sport', 'booking_status'],
  faq_item_opened: ['item_id', 'item_index'],
  language_changed: ['language'],
  support_link_opened: ['destination'],
  booking_created_server: [
    'booking_id',
    'user_id',
    'venue_id',
    'sport',
    'value',
    'currency',
  ],
  booking_cancelled_server: ['booking_id', 'venue_id', 'reason'],
  booking_refunded_server: ['booking_id', 'value', 'currency'],
  payment_status_changed_server: [
    'booking_id',
    'payment_id',
    'from_status',
    'to_status',
    'value',
    'currency',
  ],
  tournament_registration_created_server: [
    'registration_id',
    'tournament_id',
    'sport',
  ],
  canteen_order_created_server: [
    'order_id',
    'venue_id',
    'booking_id',
    'value',
    'currency',
  ],
  canteen_order_status_changed_server: [
    'order_id',
    'from_status',
    'to_status',
  ],
  navigation_tab_selected: ['tab_name', 'previous_tab'],
  analytics_period_changed: ['from_period', 'to_period'],
  analytics_refreshed: ['period', 'result', 'duration_ms'],
  business_link_copied: ['location_id', 'result'],
  business_link_shared: ['location_id', 'result'],
  analytics_detail_opened: ['destination', 'period'],
  booking_create_started: ['source_screen', 'location_id'],
  booking_create_completed: ['location_id', 'booking_type', 'source_screen'],
  booking_create_failed: ['step', 'reason_code', 'http_status'],
  booking_opened: ['source_screen', 'booking_status'],
  booking_payment_updated: ['result', 'payment_status'],
  booking_checked_out: ['result', 'overtime_applied'],
  search_used: ['screen_name', 'query_length', 'result_count'],
  filter_applied: ['screen_name', 'filter_name', 'filter_value'],
  retry_selected: ['screen_name', 'operation'],
  location_opened: ['location_id', 'source_screen'],
  location_create_completed: ['location_id'],
  location_update_completed: ['location_id'],
  facility_create_completed: ['location_id', 'facility_type'],
  facility_update_completed: ['location_id', 'facility_type'],
  user_create_completed: ['location_id', 'role'],
  user_update_completed: ['location_id', 'role'],
  user_status_changed: ['location_id', 'status'],
  customer_opened: ['location_id', 'source_screen'],
  asset_create_completed: ['location_id', 'asset_type'],
  asset_update_completed: ['location_id', 'asset_type'],
  asset_delete_completed: ['location_id', 'asset_type'],
  low_stock_viewed: ['location_id'],
  expense_create_completed: ['location_id', 'category'],
  expense_update_completed: ['location_id', 'category'],
  canteen_item_create_completed: ['location_id'],
  canteen_item_update_completed: ['location_id'],
  tournament_create_started: ['location_id', 'source_screen'],
  tournament_create_completed: ['location_id'],
  tournament_registration_updated: ['location_id', 'result'],
  tournament_stage_generated: ['location_id', 'stage_type'],
  match_score_saved: ['location_id', 'result'],
  theme_changed: ['theme'],
  profile_photo_changed: ['result'],
  team_access_opened: ['location_id'],
  booking_slots_opened: ['location_id'],
};

export function allowedPropertyKeysForEvent(eventName: string): Set<string> | null {
  const keys = EVENT_PROPERTY_KEYS[eventName];
  return keys ? new Set(keys) : null;
}

export function isAllowedEventName(eventName: string): boolean {
  return ALLOWED_EVENT_NAMES.has(eventName);
}

export function isVendorEventName(eventName: string): boolean {
  return VENDOR_EVENT_NAME_SET.has(eventName);
}

export function toAnalyticsSport(sport: string | null | undefined): string | null {
  const raw = (sport ?? '').trim();
  if (!raw) return null;
  if (raw === 'table-tennis') return 'table_tennis';
  return raw.replace(/-/g, '_');
}
